### ISSUE TITLE
cmd support for ipk

### ISSUE THREAD

**Issue by heyimyunyl** [RayCarrot/RayCarrot.RCP.Metro#1]
hi ray, i wonder if you could make a seperate CLI/CMD IPK unpacker/creator so we can use your utility in our Just Dance song creator tool's IPK creation part. we use unpakke and its compression sucks

**Comment by RayCarrot** [comment]
I'm currently reworking the archive system in RCP, but I won't be adding any launch arguments for it due to the way RCP is built.

The majority of the code used to handle the IPK files exists in the [RayCarrot.Rayman](https://github.com/RayCarrot/RayCarrot.Rayman) library, so you can reference that to make a simple repack tool. The class **UbiArtIpkData** has methods for serializing the IPK file table and repacking it with new/modified files.
