### ISSUE TITLE
Rayman 2 Anti-Pirate Head Option missing?

### ISSUE THREAD

**Issue by TheWitheredStriker** [RayCarrot/RayCarrot.RCP.Metro#13]
Hello, I recently bought Rayman 2 from GOG.com and went to play it, but despite owning a legal copy of the game, I still get the pirate head anti-piracy screen. I've been told that the Rayman Control Panel has an option to bypass this, but I don't see such an option anywhere:

![image](https://user-images.githubusercontent.com/38614982/200359405-a54db4f3-b557-4b33-b1f5-1a06b661f4d3.png)

My user level is at Technical. 

Hoping to hear from you soon!

**Comment by TheWitheredStriker** [comment]
Never mind, I didn't look far enough :P it's in the Patches menu, from the arrow dropdown. My bad!

**Comment by RayCarrot** [comment]
Hi! Sorry for the confusion. Yeah in the latest version I replaced some of the utilities with patches in an attempt to normalize how file replacement and modifications are handled by the program.
I can't guarantee this patch will solve your issue though, but it's worth trying! The game has several things which can trigger the pirate head and this patch mainly removes the one caused by the game checking if the files have been modified. This is mostly so other patches, like the texture upscales, can work.

**Comment by TheWitheredStriker** [comment]
Yeah, I did upscale the textures so that's probably why I got the pirate head. I'll play the game again later on and tell you if I still get it.
