### ISSUE TITLE
Problems while editing Just Dance 2014 files from WII

### ISSUE THREAD

**Issue by dimasah901** [RayCarrot/RayCarrot.RCP.Metro#23]
When i try to open an IPK archive of Just Dance 2014 WII, names and paths of files are mixed up.
For example, file **todo.tpl.ckd** located in **cache/itf_cooked/wii/enginedata/actortemplates** is shown as a file **cache/itf_cooked/wii/enginedata/actortemplates** located inside **todo.tpl.ckd**.

Example:
![image](https://github.com/RayCarrot/RayCarrot.RCP.Metro/assets/93038732/ec92c0ec-4829-460b-b67f-e2be68c73608)

Edit: one way to fix it is to add an option **Just Dance 2014 (Wii)** inside **UbiArt Archives (.ipk)** and replace each file's path with it's name and file's name with it's path.

**Comment by RayCarrot** [comment]
Hi! Which game mode are you currently opening the .ipk file with? I don't have the game files myself, but since it seems to load the contents correctly with the game mode you chose I can just add an option for Just Dance 2014 with the path fields swapped like you said. In general the Just Dance games appear to store the path fields in reverse order from the other games,

**Comment by dimasah901** [comment]
Sorry for the late reply. I am opening the file with just dance 2017 Wii u.

**Comment by RayCarrot** [comment]
Have you tried opening it with other game modes? The Just Dance 2017 one specifically swaps the paths and file names, which none of the other options do.
