### ISSUE TITLE
Rayman 1 Per-Level Soundtrack - PluMGMK's TSR implementation

### ISSUE THREAD

**Issue by Mystyle-48** [RayCarrot/RayCarrot.RCP.Metro#24]
Rather than using a patched DOSBox build to implement the Per-Level Soundtrack feature for Rayman 1, have you considered using PluMGMK’s [TSR](https://github.com/PluMGMK/rayman-tpls-tsr)? It provides a custom CD image with the complete soundtrack and a native DOS executable that runs alongside `RAYMAN.EXE` to make the required changes. I've tested it a bit and it appears to work well.

**Comment by RayCarrot** [comment]
Hi! Yep, that's actually been on my todo list for some time now 🙂 I haven't had a chance to really check it out yet though, but last I remember it didn't have all features that the patched DOSBox version did? A quick look at the repo seems to suggest the MIDI tracks aren't included in this version. Personally I don't think that's a big deal though. The main benefit is to avoid having all music tracks from a world play one after another in every map like they do by default on PC.
I also recently had someone ask if I could update the Per-Level Soundtrack utility to support other DOSBox versions, such as Dosbox Staging, which using the TSR variant would automatically resolve since it would no longer be dependent on a single DOSBox build then.

So yeah, I'll definitely be looking into this more and talking to Plum about it to see what the current state of the project is.

**Comment by RayCarrot** [comment]
The per-level soundtrack tool in RCP has now been updated to use the new TSR version by PluMGMK. This is available in the [latest beta](https://github.com/RayCarrot/RayCarrot.RCP.Metro/releases/tag/14.2.0.1).

**Comment by Mystyle-48** [comment]
Nice! I have been using PluMGMK's updated TSR for a few weeks, and it solves virtually all the shortcomings of the previous TPLS implementations. Thank you for bringing this to RCP. 😄
