### ISSUE TITLE
Admin Issues

### ISSUE THREAD

**Issue by Torchite** [RayCarrot/RayCarrot.RCP.Metro#25]
the Program opens as admin, but doesn't have privileges to modify the game.

**Comment by Torchite** [comment]
I was trying to modify Rayman Legends btw

**Comment by RayCarrot** [comment]
Where is the game installed on your computer? Which mod are you trying to apply?
It would also help if you could upload the log file after attempting to apply the mods. It's located at `%LocalAppData%\Rayman Control Panel\RCP_Metro\Temp\Log.txt`.

**Comment by Torchite** [comment]
Shadow Ray mod
[Log_archived.15.txt](https://github.com/RayCarrot/RayCarrot.RCP.Metro/files/14548027/Log_archived.15.txt)

**Comment by RayCarrot** [comment]
Where is the game installed on your computer? The default location (`C:\Program Files (x86)\Steam\steamapps\common\Rayman Legends`) or somewhere else? Do any mods work to install?

**Comment by Torchite** [comment]
I have it installed from Ubisoft Connect, and I also have a second drive where I fit my big game, so...

D:\UBISOFT\Ubisoft Game Launcher\games\Rayman Legends

**Comment by RayCarrot** [comment]
I thought the issue could be that the game was not on your C drive. But I just tested myself and it works fine for me when on an external drive. So that's odd. The log sadly didn't help much since the actual error data didn't get logged. All I see is that it fails to move a directory.

Some things that come to mind:
- Do you have enough space on both your C and D drives? At least 12 GB is good to have for all the repacking.
- Make sure the game, and perhaps also Ubisoft Connect, is not running while applying the mods
- You said you tried running RCP as admin, but maybe try checking the file permissions for your game so they're not set to read-only or something
- You could try temporarily disabling your anti-virus in case that's interfering. Although honestly I doubt that's the issue since I haven't had anyone else run into that before.

**Comment by Torchite** [comment]
ah. I forgot the read only thing is a thing, so I went to fix that, but it keeps changing back to read only. idk how to fix that.

**Comment by RayCarrot** [comment]
That's too bad. I'm sorry but I don't really know what else the issue could be. It's annoying that the actual error message isn't exposed in the log there. I could fix that for the next update, so hopefully then it'll become easier investigating it. I don't know when that will be released though. If you want to try getting it to work beforehand you could maybe try re-installing the game on your C drive in case that would help, but I'm not to sure it will at this point.

**Comment by Torchite** [comment]
I figured it out before I read that, I had to move it to C drive.

**Comment by RayCarrot** [comment]
Oh okay. I'm glad that worked! Although I'm still curious why it didn't work before. Anyway, I'll close the issue then since it's solved for you.
