### ISSUE TITLE
Error when trying to install certain mods on Rayman Legends.

### ISSUE THREAD

**Issue by Noenko** [RayCarrot/RayCarrot.RCP.Metro#36]
Whenever I try and install the mods "Uncompressed PS4 Assets" or "Fixed Assets" the launcher does not install them successfully, instead giving me the following error messages:

Uncompressed PS4 Assets: https://imgur.com/a/BJFhbKE

Fixed Assets: https://imgur.com/a/v5WrhUI

This happens whether I am using the launcher in Admin mode or not, I tried it with both the Uplay release and Steam, still get the same error.

Tried removing ".rcp_mods" and reinstalling the mod, this does not fix it either.

**Comment by RayCarrot** [comment]
Hi! That's odd. There have been issues in the past with the file length limit on Windows, but I don't think this is it. Does this happen with all mods that you try and install? Is the game installed on your C drive or elsewhere? Also what happens if you try and install the mod but leave it unchecked?

**Comment by Noenko** [comment]
I have Rayman Legends Installed on my "G:" drive, but I couldn't install these mods when I used my Ubisoft Launcher installation either that was on the "C:" drive.

Some mods seem to install. I got "Better Transparent Textures", "DualShock 3 HUD" "No More Intro" to work.

This error happens after the installation phase, so I can't select it in the "Library".

I checked the ".rcp_mods\mods" folder, and the mod has a folder in there, it doesn't show up in the Launcher.

Here is the log:
[Log.txt](https://github.com/user-attachments/files/17993909/Log.txt)

**Comment by RayCarrot** [comment]
I think it might be related to the file path being too long when copied onto your G drive. What is the full path where you have Rayman Legends installed? Also when you tried having the game installed on your C drive, what error did you get then? It should have been a different one.

**Comment by Noenko** [comment]
> I think it might be related to the file path being too long when copied onto your G drive. What is the full path where you have Rayman Legends installed? Also when you tried having the game installed on your C drive, what error did you get then? It should have been a different one.

The location that didn't work was "G:\Launcher\Steam\steamapps\common\Rayman Legends", 
I now installed Rayman Origins into "C:\SteamLibrary\steamapps\common\Rayman Legends" and both mods work.

My "C:" and "G:" are on the same NVME SSD if that helps anything.

**Comment by RayCarrot** [comment]
Yeah it's a file path length issue then. It's pretty annoying that most Windows APIs still have the 260 character limit for paths. I think once I migrate RCP over to .NET 9 that most of this should work better since that uses more modern file IO APIs. In the meantime I'll close this issue since there's not much more I can do about it atm. I'm glad it works for you now though and sorry about the inconvenience!

**Comment by Noenko** [comment]
Update: I tried installing the mods to "G:\SteamLibrary\steamapps\common\Rayman Legends" and this did not work.

It seems to only install these mods on "C:\SteamLibrary\steamapps\common\Rayman Legends".

**Comment by RayCarrot** [comment]
Yeah I think the file path length is mainly an issue when not on the C drive since the file operations work differently then.

**Comment by Noenko** [comment]
Ah I see, I'll just use the "C:" drive for Rayman Legends then.
Thank you for the help!
