### ISSUE TITLE
Install Rayman 1 from CD

### ISSUE THREAD

**Issue by kscheel** [RayCarrot/RayCarrot.RCP.Metro#7]
Hey, first of all thanks creating this great tool! :)

I was hoping I'd be able use my German Rayman CD to install the game with RCP. But I guess that's not supported for now?

Trying to run the installer from the CD yields an error about "CONFIG.EXE". So it would be really nice if Rayman Control Panel could do the installation :)

I also own the GOG version (Rayman Forever) but here I miss the intro video and switching to German (through Rayman Control Panel) did not work, so I thought I'd just use my old CD.

Kind regards!

**Comment by icup321** [comment]
Hey, so this is kind of a self-plug :P but I made a patch for the GOG version that re-adds missing content like the intro video and French and German languages. You still need to use Rayman Control Panel to change the language though, but it should work just fine: https://www.mediafire.com/file/39t6333je0fhjnh/Rayman_Forever_DX%252B.7z/file

**Comment by RayCarrot** [comment]
Currently RCP doesn't support installing the Rayman 1 games from disc, though it's something I've been planning to add. For that I would need to rewrite the disc installer code though since it's not very flexible at the moment, so it might take a while before I get around to doing that.
In the meantime you can either use an unofficial patch like what @icup321 mentioned, install the game through DOSBox or manually copy over the files. If you choose the latter then what you'll need to do is to copy over the disc files for the respective games (Rayman 1 will be in a RAYMAN folder, Rayman Designer in a RAYKIT folder etc.) to your computer. Then add that folder in RCP, set the mount path to your disc drive and save the config in RCP with the recommended options.

**Comment by kscheel** [comment]
@RayCarrot It works! :D That was easy enought, thanks for the instructions! It runs even better than the GOG version where I had noticed some stutters/slowdowns :)

Btw, I wasn't quite happy after loading the recommende DOSBox settings. I changed a few more things to get the game to display nicely:

* enabled fullscreen
* enabeld fullscreen double buffering (there was tearing visible withouth this)
* changed output to "ddraw" (now it scales correctly and colors are displayed correctly)
* set Fullscreen resolution to "Desktop"

I don't really know anything about DOSBox so maybe these are just the settings that seem to work best for me  :)

@icup321 Thanks to you too for the patch, I'll probably try it as soon as I'm fed up with inserting the CD in order play the game. But for not it really makes me happy that I was able to make use of my old CD again :D

**Comment by RayCarrot** [comment]
The recommended DOSBox settings were mostly copied from what GOG defaults to I think. You can view what it does [here](https://github.com/RayCarrot/RayCarrot.RCP.Metro/blob/master/src/RayCarrot.RCP.Metro/Emulators/DOSBox/Emulator_DOSBox_ConfigViewModel.cs#L499). I haven't experienced any issues with them myself, but I might look into it more some time. What's more important is using the recommended settings for the Rayman 1 config since that sets the driver related values to what works best in DOSBox (without those the game might run without sound). Glad you got it all working though!
